"""Add pod_filename to Order and WarehouseStock

Revision ID: 07684e0f9c0b
Revises: 70c6b036a994
Create Date: 2025-05-27 16:45:01.019347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07684e0f9c0b'
down_revision = '70c6b036a994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pod_filename', sa.String(length=120), nullable=True))

    with op.batch_alter_table('warehouse_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pod_filename', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_stock', schema=None) as batch_op:
        batch_op.drop_column('pod_filename')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('pod_filename')

    # ### end Alembic commands ###
