"""Initial migration with DeliveredGoods extended fields

Revision ID: 3f78f71ef356
Revises: 
Create Date: 2025-06-27 15:27:12.836399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f78f71ef356'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivered_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('client', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pos_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('customer_ref', sa.String(length=50), nullable=True))
        batch_op.drop_column('stockreport_order_id')

    with op.batch_alter_table('warehouse_stock', schema=None) as batch_op:
        batch_op.drop_column('signature_client')
        batch_op.drop_column('signature_date_warehouse')
        batch_op.drop_column('signature_date_client')
        batch_op.drop_column('signature_warehouse')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_warehouse', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('signature_date_client', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('signature_date_warehouse', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('signature_client', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('delivered_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stockreport_order_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('customer_ref')
        batch_op.drop_column('pos_no')
        batch_op.drop_column('client')
        batch_op.drop_column('warehouse_address')

    # ### end Alembic commands ###
