"""Add notes field to DeliveredGoods

Revision ID: 70c6b036a994
Revises: 8af089c11e0d
Create Date: 2025-05-16 12:41:16.602077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c6b036a994'
down_revision = '8af089c11e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivered_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivered_goods', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
