"""Add is_manual field to WarehouseStock

Revision ID: 8af089c11e0d
Revises: 9aba98f2d35c
Create Date: 2025-05-16 11:41:31.747705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af089c11e0d'
down_revision = '9aba98f2d35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_manual', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_stock', schema=None) as batch_op:
        batch_op.drop_column('is_manual')

    # ### end Alembic commands ###
