"""Add missing fields to WarehouseStock

Revision ID: 9274ba7aa605
Revises: 3f78f71ef356
Create Date: 2025-06-27 15:53:14.193991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9274ba7aa605'
down_revision = '3f78f71ef356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('warehouse_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('client', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pos_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('customer_ref', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_stock', schema=None) as batch_op:
        batch_op.drop_column('customer_ref')
        batch_op.drop_column('pos_no')
        batch_op.drop_column('client')
        batch_op.drop_column('warehouse_address')

    # ### end Alembic commands ###
