"""Rename original_id to original_order_id

Revision ID: 949e40ad7ffa
Revises: 9f5e11a006c2
Create Date: 2025-06-04 13:51:23.465244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949e40ad7ffa'
down_revision = '9f5e11a006c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_order_id', sa.Integer(), nullable=True))
        batch_op.drop_column('original_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('original_order_id')

    # ### end Alembic commands ###
