"""Allow null order_number

Revision ID: 9aba98f2d35c
Revises: ecc75747be9e
Create Date: 2025-05-15 17:01:27.805220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aba98f2d35c'
down_revision = 'ecc75747be9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('required_delivery',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('terms_of_delivery',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('etd',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('eta',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('eta',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('etd',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('terms_of_delivery',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('required_delivery',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('order_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
