"""Add transport field to DeliveredGoods

Revision ID: 9e58ff99b494
Revises: e004b29ab6ad
Create Date: 2025-05-14 16:06:45.557502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e58ff99b494'
down_revision = 'e004b29ab6ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivered_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivered_goods', schema=None) as batch_op:
        batch_op.drop_column('transport')

    # ### end Alembic commands ###
