"""Add original_id and source to ArchivedOrder

Revision ID: 9f5e11a006c2
Revises: 1c6930380b74
Create Date: 2025-06-04 13:39:16.341627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5e11a006c2'
down_revision = '1c6930380b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=100), nullable=True))
        batch_op.drop_column('original_order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_order_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('source')
        batch_op.drop_column('original_id')

    # ### end Alembic commands ###
