"""Add notes and transport to WarehouseStock

Revision ID: e004b29ab6ad
Revises: 
Create Date: 2025-05-14 12:47:16.884273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e004b29ab6ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('transport', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_stock', schema=None) as batch_op:
        batch_op.drop_column('transport')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
