"""Set quantity as String for all tables

Revision ID: ecc75747be9e
Revises: 274a85bd7d7e
Create Date: 2025-05-15 16:51:28.731897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc75747be9e'
down_revision = '274a85bd7d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivered_goods', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('warehouse_stock', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_stock', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.String(length=50),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.String(length=50),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('delivered_goods', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.String(length=50),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
